#- lineinfile: dest=/etc/postfix/main.cf regexp=^relayhost= line=relayhost = imhq05b.omni
#- lineinfile: dest=/etc/postfix/main.cf line="relayhost = [imhq05b.omni]"
- copy: src=main.cf dest=/etc/postfix/main.cf owner=root group=root mode=0755 backup=yes

- systemd:
    name: postfix
    state: started
    enabled: True
