  - name: install cloudera manager-agent-daemons
    yum: name={{ item }} state=present
    with_items:
    - /tmp/cloudera-manager-agent-5.3.0-1.cm530.p0.166.el6.x86_64.rpm
    - /tmp/cloudera-manager-daemons-5.3.0-1.cm530.p0.166.el6.x86_64.rpm
