---
# tasks file for soe
- file: path=/admin state=directory mode=0755

- copy: src=.mailrc dest=/home/ec2-user owner=ec2-user group=ec2-user mode=0755 backup=yes

- copy: src=bashrc dest=/etc/bashrc owner=root group=root mode=0755 backup=yes

- copy: src=diskspace.sh dest=/admin/diskspace.sh owner=root group=root mode=0755 backup=yes

- file: src=/tmp/{{ item.src }} dest={{ item.dest }} owner=root group=root mode=0755
  with_items:
    - { src: 'bashlog.sh', dest: '/etc/profile.d/bashlog.sh' }
    - { src: 'bashrc', dest: '/etc/bashrc' }
    - { src: 'findlarge.sh', dest: '/admin/findlarge.sh' }
    - { src: 'main.cf', dest: '/etc/postfix/main.cf' }

#- command: /admin/r.sh
- include: gather_info.yml

