
- user: name={{ item }} comment={{ item }} groups=wheel
  with_items:
  - "{{ sysadmin }}"
  tags: sysadmin

- user: name={{ item }} comment={{ item }} groups=users state=absent
  with_items:
  - "{{ users }}"
  tags: username

- authorized_key: user={{ item }} key="{{ lookup('file', '~/ansible/files/{{ item }}.pub') }}"
  with_items:
  - "{{ users }}"
  - "{{ sysadmin }}"
  tags: ssh_key

- include: new-server.yml
  tags: new-server
